# Teste de Performance -3

Uso de IAs: Sinal Vermelho 🔴

Todas as partes deste trabalho devem ser da autoria do aluno\. Qualquer uso de ferramentas generativas de IA, como ChatGPT, é proibido\. O uso de IA generativa será considerado má conduta acadêmica e estará sujeito à aplicação do código disciplinar, pois as tarefas deste trabalho foram elaboradas para desafiar o aluno a desenvolver conhecimentos de base, pensamento crítico e habilidades de resolução de problemas\. O uso da tecnologia de IA limitaria sua capacidade de desenvolver essas competências e de atingir os objetivos de aprendizagem desta disciplina\.

## Tabelas de Referência

Para todos os exercícios, utilize as estruturas de tabelas abaixo:

In [1]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'DROP TABLE IF EXISTS vendedores;\nDROP TABLE IF EXISTS pedidos;\nDROP TABLE IF EXISTS clientes;\nDROP TABLE IF EXISTS produtos;\n\n-- TABELA 1: PRODUTOS\nCREATE TABLE produtos (\n    id INT PRIMARY KEY,\n    nome TEXT,\n    categoria TEXT,\n    preco_unitario DECIMAL(10,2),\n    estoque INT\n);\n\nINSERT INTO produtos VALUES \n(1, \'Teclado Mecânico\', \'Periféricos\', 250.00, 15),\n(2, \'Mouse Gamer\', \'Periféricos\', 120.00, 0),\n(3, \'Monitor 24pol\', \'Monitores\', 890.00, 8),\n(4, \'Cabo HDMI 2m\', \'Acessórios\', 45.00, 50),\n(5, \'Cadeira Office\', \'Móveis\', 1200.00, 3),\n(6, \'Webcam HD\', \'Periféricos\', 310.00, 12),\n(7, \'Notebook Pro\', \'Computadores\', 5500.00, 5),\n(8, \'Headset USB\', \'Áudio\', 180.00, 20),\n(9, \'Mesa Digitalizadora\', \'Periféricos\', 450.00, 7),\n(10, \'SSD 512GB\', \'Hardware\', 290.00, 25),\n(11, \'Suporte Monitor\', \'Acessórios\', 130.00, 10),\n(12, \'Luminária LED\', \'Acessórios\', 85.00, 0);\n\n-- TABELA 2: CLIENTES\nCREATE TABLE clientes (\n    id_cliente INT PRIMARY KEY,\n    nome_completo TEXT,\n    cidade TEXT,\n    estado TEXT,\n    tipo_plano TEXT\n);\n\nINSERT INTO clientes VALUES \n(101, \'Ana Silva\', \'São Paulo\', \'SP\', \'Gold\'),\n(102, \'Bruno Costa\', \'Curitiba\', \'PR\', \'Silver\'),\n(103, \'Carla Souza\', \'São Paulo\', \'SP\', \'Free\'),\n(104, \'Daniel Oliveira\', \'Rio de Janeiro\', \'RJ\', \'Gold\'),\n(105, \'Eduardo Lima\', \'Belo Horizonte\', \'MG\', \'Silver\'),\n(106, \'Fernanda Dias\', \'Porto Alegre\', \'RS\', \'Gold\'),\n(107, \'Gabriel Santos\', \'São Paulo\', \'SP\', \'Free\'),\n(108, \'Helena Rocha\', \'Salvador\', \'BA\', \'Silver\'),\n(109, \'Igor Mendes\', \'Recife\', \'PE\', \'Gold\'),\n(110, \'Julia Castro\', \'Curitiba\', \'PR\', \'Free\'),\n(111, \'Kevin Nunes\', \'Rio de Janeiro\', \'RJ\', \'Silver\'),\n(112, \'Larissa Melo\', \'São Paulo\', \'SP\', \'Gold\');\n\n-- TABELA 3: PEDIDOS\nCREATE TABLE pedidos (\n    num_pedido INT PRIMARY KEY,\n    data_pedido DATE,\n    id_cliente INT,\n    valor_total DECIMAL(10,2),\n    status TEXT\n);\n\nINSERT INTO pedidos VALUES \n(5001, \'2024-01-05\', 101, 250.00, \'ENTREGUE\'),\n(5002, \'2024-01-10\', 104, 1200.00, \'ENVIADO\'),\n(5003, \'2024-01-12\', 102, 45.00, \'ENTREGUE\'),\n(5004, \'2024-01-15\', 109, 5500.00, \'PROCESSANDO\'),\n(5005, \'2024-01-18\', 103, 120.00, \'CANCELADO\'),\n(5006, \'2024-01-20\', 112, 310.00, \'ENTREGUE\'),\n(5007, \'2024-01-22\', 105, 890.00, \'ENVIADO\'),\n(5008, \'2024-01-25\', 108, 130.00, \'ENTREGUE\'),\n(5009, \'2024-01-26\', 111, 290.00, \'PROCESSANDO\'),\n(5010, \'2024-01-28\', 106, 180.00, \'ENTREGUE\'),\n(5011, \'2024-01-30\', 107, 450.00, \'CANCELADO\'),\n(5012, \'2024-02-03\', 103, 257.00, \'CANCELADO\'),\n(5013, \'2024-02-05\', 110, 85.00, \'ENVIADO\');\n\n-- TABELA 4: VENDEDORES\nCREATE TABLE vendedores (\n    id_vendedor INT PRIMARY KEY,\n    nome_vendedor TEXT,\n    regiao TEXT,\n    vendas_mes INT,\n    meta_atingida TEXT\n);\n\nINSERT INTO vendedores VALUES \n(1, \'Ricardo\', \'Sudeste\', 45, \'SIM\'),\n(2, \'Marcia\', \'Sul\', 28, \'NAO\'),\n(3, \'Roberto\', \'Sudeste\', 52, \'SIM\'),\n(4, \'Aline\', \'Nordeste\', 33, \'SIM\'),\n(5, \'Jose\', \'Centro-Oeste\', 19, \'NAO\'),\n(6, \'Beatriz\', \'Sudeste\', 60, \'SIM\'),\n(7, \'Carlos\', \'Sul\', 41, \'SIM\'),\n(8, \'Daniela\', \'Nordeste\', 25, \'NAO\'),\n(9, \'Fabio\', \'Norte\', 12, \'NAO\'),\n(10, \'Gisele\', \'Sudeste\', 38, \'SIM\'),\n(11, \'Hugo\', \'Sul\', 22, \'NAO\'),\n(12, \'Ivone\', \'Nordeste\', 50, \'SIM\');\n',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   Count
0     12

### Exercício 1 

**Contexto**
O gestor de estoque da empresa TechStore precisa realizar uma auditoria completa em todo o catálogo de produtos cadastrados. Para garantir que nenhum item seja esquecido no relatório de inventário, ele solicitou a listagem integral da tabela de produtos para conferência manual. O impacto esperado é a transparência total sobre o que está disponível no banco de dados.

**Dados disponíveis**
Tabela: `produtos`
Colunas: `id`, `nome`, `categoria`, `preco_unitario`, `estoque`

**Tarefa**
* Escreva uma query que retorne todas as colunas e todas as linhas da tabela de produtos.

In [7]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

df_1 = _dntk.execute_sql(
  'SELECT \n    ID, \n    NOME, \n    CATEGORIA, \n    PRECO_UNITARIO, \n    ESTOQUE\nFROM PRODUTOS',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)
df_1

    id                 nome     categoria  preco_unitario  estoque
0    1     Teclado Mecânico   Periféricos           250.0       15
1    2          Mouse Gamer   Periféricos           120.0        0
2    3        Monitor 24pol     Monitores           890.0        8
3    4         Cabo HDMI 2m    Acessórios            45.0       50
4    5       Cadeira Office        Móveis          1200.0        3
5    6            Webcam HD   Periféricos           310.0       12
6    7         Notebook Pro  Computadores          5500.0        5
7    8          Headset USB         Áudio           180.0       20
8    9  Mesa Digitalizadora   Periféricos           450.0        7
9   10            SSD 512GB      Hardware           290.0       25
10  11      Suporte Monitor    Acessórios           130.0       10
11  12        Luminária LED    Acessórios            85.0        0

### Exercício 2 

**Contexto**

A equipe de marketing da TechStore está preparando uma nova newsletter focada na precificação dos itens da loja. Para estruturar o layout do e‑mail, o designer precisa apenas dos nomes dos produtos e seus respectivos preços unitários. Como a campanha inicial será direcionada apenas para produtos em alta demanda, é necessário limitar a consulta aos itens de **categoria 'Periféricos'** com mais de 5 unidades em estoque. Essa seleção reduz o volume de dados desnecessários para a tarefa criativa.

**Dados disponíveis**

Tabela: `produtos`  
Colunas: `id`, `nome`, `categoria`, `preco_unitario`, `estoque`

**Tarefa**

* Escreva uma query que retorne as colunas `nome` e `preco_unitario` dos produtos cuja `categoria` seja `'Periféricos'` **e** o `estoque` seja maior que 5.

In [10]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT \n    NOME,  \n    PRECO_UNITARIO\nFROM PRODUTOS\nWHERE 1=1\nAND CATEGORIA = \'Periféricos\'\nAND ESTOQUE > 5',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

                  nome  preco_unitario
0     Teclado Mecânico           250.0
1            Webcam HD           310.0
2  Mesa Digitalizadora           450.0

### Exercício 3 

**Contexto**
O coordenador do setor de periféricos notou uma alta rotatividade nos itens de entrada e precisa validar especificamente essa categoria. Para organizar a reposição nas prateleiras, ele solicitou uma listagem contendo apenas os produtos que pertencem estritamente à categoria 'Periféricos'. O objetivo é isolar esses itens para o planejamento logístico imediato.

**Dados disponíveis**
Tabela: `produtos`
Colunas: `id`, `nome`, `categoria`, `preco_unitario`, `estoque`

**Tarefa**
* Escreva uma query que retorne todas as colunas dos produtos cujo valor da coluna `categoria` seja exatamente 'Periféricos'.

In [13]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT \n    ID, \n    NOME, \n    CATEGORIA, \n    PRECO_UNITARIO, \n    ESTOQUE\nFROM PRODUTOS\nWHERE 1=1\nAND CATEGORIA = \'Periféricos\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   id                 nome    categoria  preco_unitario  estoque
0   1     Teclado Mecânico  Periféricos           250.0       15
1   2          Mouse Gamer  Periféricos           120.0        0
2   6            Webcam HD  Periféricos           310.0       12
3   9  Mesa Digitalizadora  Periféricos           450.0        7

### Exercício 4 

**Contexto**

O diretor financeiro identificou a necessidade de liquidar produtos caros que estão ocupando muito espaço físico sem rotatividade. Para a estratégia de promoção, ele precisa identificar itens com preço unitário superior a 500,00 e que ainda possuam menos de 10 unidades no estoque atual. Além disso, devem ser excluídos os itens da categoria 'Periféricos', pois esses já estão contemplados em outra campanha. O impacto esperado é a liberação de capital de giro e espaço no armazém.

**Dados disponíveis**

Tabela: `produtos`  
Colunas: `id`, `nome`, `categoria`, `preco_unitario`, `estoque`

**Tarefa**

* Escreva uma query que retorne o `nome`, a `categoria` e o `estoque` dos produtos com `preco_unitario` maior que 500,00 **e** `estoque` menor que 10 **e** `categoria` diferente de `'Periféricos'`.

In [16]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT \n    NOME, \n    CATEGORIA, \n    ESTOQUE\nFROM PRODUTOS\nWHERE 1=1\nAND PRECO_UNITARIO > 500\nAND ESTOQUE < 10\nAND CATEGORIA <> \'Periféricos\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

             nome     categoria  estoque
0   Monitor 24pol     Monitores        8
1  Cadeira Office        Móveis        3
2    Notebook Pro  Computadores        5

### Exercício 5 

**Contexto**
O setor de logística da TechStore está planejando uma rota de entrega otimizada para a região metropolitana de São Paulo. Para mapear a densidade de consumidores, o analista de dados deve extrair a lista de todos os clientes que residem no estado de 'SP'. Essa informação é vital para o cálculo de custos de frete regional.

**Dados disponíveis**
Tabela: `clientes`
Colunas: `id_cliente`, `nome_completo`, `cidade`, `estado`, `tipo_plano`

**Tarefa**
* Escreva uma query que retorne o nome completo e a cidade dos clientes que moram no estado ('estado') 'SP'.

In [19]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT \n    NOME_COMPLETO,\n    CIDADE\nFROM CLIENTES\nWHERE 1=1\nAND ESTADO = \'SP\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

    nome_completo     cidade
0       Ana Silva  São Paulo
1     Carla Souza  São Paulo
2  Gabriel Santos  São Paulo
3    Larissa Melo  São Paulo

### Exercício 6 

**Contexto**

O gerente de expansão da empresa está analisando o potencial de mercado na região Sul do Brasil, focando inicialmente nos estados do Paraná e Rio Grande do Sul. Para realizar uma pesquisa de satisfação direcionada, ele precisa identificar todos os clientes cadastrados que morem em 'PR' ou 'RS'. Além disso, para comparar a experiência de clientes com planos premium, devem ser incluídos também todos os clientes com plano `'Gold'` independentemente do estado. O resultado ajudará na definição de novas parcerias locais.

**Dados disponíveis**

Tabela: `clientes`  
Colunas: `id_cliente`, `nome_completo`, `cidade`, `estado`, `tipo_plano`

**Tarefa**

* Escreva uma query que selecione todas as colunas dos clientes cujo `estado` seja 'PR' **ou** 'RS' **ou** cujo `tipo_plano` seja `'Gold'`.

In [25]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    ID_CLIENTE,\n    NOME_COMPLETO,\n    CIDADE,\n    ESTADO,\n    TIPO_PLANO\nFROM CLIENTES\nWHERE ESTADO IN (\'PR\', \'RS\')\nOR TIPO_PLANO = \'Gold\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   id_cliente    nome_completo          cidade estado tipo_plano
0         101        Ana Silva       São Paulo     SP       Gold
1         102      Bruno Costa        Curitiba     PR     Silver
2         104  Daniel Oliveira  Rio de Janeiro     RJ       Gold
3         106    Fernanda Dias    Porto Alegre     RS       Gold
4         109      Igor Mendes          Recife     PE       Gold
5         110     Julia Castro        Curitiba     PR       Free
6         112     Larissa Melo       São Paulo     SP       Gold

### Exercício 7 

**Contexto**

A equipe de Customer Success quer focar em converter usuários que ainda não experimentaram a experiência completa da plataforma, ou seja, os usuários 'Free'. Para uma ação de limpeza de base de dados segmentada, o analista precisa listar todos os clientes que **não** possuam o plano 'Free' **e** que também não residam no estado de 'SP'. Isso permitirá uma visão clara da base de clientes pagantes ativos em outras regiões.

**Dados disponíveis**

Tabela: `clientes`  
Colunas: `id_cliente`, `nome_completo`, `cidade`, `estado`, `tipo_plano`

**Tarefa**

* Escreva uma query que retorne o nome, a cidade e o estado de todos os clientes em que o `tipo_plano` seja diferente de `'Free'` **e** o `estado` seja diferente de `'SP'`.

In [31]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NOME_COMPLETO,\n    CIDADE,\n    ESTADO\nFROM CLIENTES\nWHERE TIPO_PLANO <> \'Free\' AND ESTADO <> \'SP\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

     nome_completo          cidade estado
0      Bruno Costa        Curitiba     PR
1  Daniel Oliveira  Rio de Janeiro     RJ
2     Eduardo Lima  Belo Horizonte     MG
3    Fernanda Dias    Porto Alegre     RS
4     Helena Rocha        Salvador     BA
5      Igor Mendes          Recife     PE
6      Kevin Nunes  Rio de Janeiro     RJ

### Exercício 8 

**Contexto**
A equipe de Customer Success quer focar em converter usuários que ainda não experimentaram a experiência completa da plataforma, ou seja, os usuários 'Free'. Para uma ação de limpeza de base de dados segmentada, o analista precisa listar todos os clientes que NÃO possuem o plano 'Free'. Isso permitirá uma visão clara da base de clientes pagantes ativos.

**Dados disponíveis**
Tabela: `clientes`
Colunas: `id_cliente`, `nome_completo`, `cidade`, `estado`, `tipo_plano`

**Tarefa**
* Escreva uma query que retorne o nome e o estado de todos os clientes onde o `tipo_plano` seja diferente de 'Free'.

In [34]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NOME_COMPLETO,\n    ESTADO\nFROM CLIENTES\nWHERE 1=1\nAND TIPO_PLANO = \'Free\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

    nome_completo estado
0     Carla Souza     SP
1  Gabriel Santos     SP
2    Julia Castro     PR

### Exercício 9 

**Contexto**

O departamento financeiro está auditando transações de alto valor para prevenir fraudes e garantir a segurança das operações bancárias da TechStore. O auditor solicitou uma relação de todos os pedidos cujo valor total tenha ultrapassado a marca de 1000,00 reais **e** cujo status indique que o pedido está em processamento ou já foi enviado. O impacto será a geração de um relatório de conformidade para a diretoria.

**Dados disponíveis**

Tabela: `pedidos`  
Colunas: `num_pedido`, `data_pedido`, `id_cliente`, `valor_total`, `status`

**Tarefa**

* Escreva uma query que retorne todos os detalhes dos pedidos com `valor_total` maior que 1000,00 **e** cujo `status` seja `'ENVIADO'` **ou** `'PROCESSANDO'`.

In [37]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NUM_PEDIDO,\n    DATA_PEDIDO,\n    ID_CLIENTE,\n    VALOR_TOTAL,\n    STATUS\nFROM PEDIDOS\nWHERE 1=1\nAND VALOR_TOTAL > 1000\nAND STATUS IN (\'ENVIADO\', \'PROCESSANDO\')',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   num_pedido data_pedido  id_cliente  valor_total       status
0        5002  2024-01-10         104       1200.0      ENVIADO
1        5004  2024-01-15         109       5500.0  PROCESSANDO

### Exercício 10 

**Contexto**
O setor de expedição precisa priorizar o envio de mercadorias que já foram processadas mas que representam um ticket médio elevado para a empresa. Para otimizar o fluxo de saída, o supervisor solicitou a lista de pedidos que estão com status 'ENTREGUE' e que possuem valor superior a 300.00. Isso ajuda na validação de processos concluídos com sucesso.

**Dados disponíveis**
Tabela: `pedidos`
Colunas: `num_pedido`, `data_pedido`, `id_cliente`, `valor_total`, `status`

**Tarefa**
* Escreva uma query que selecione o número do pedido e o valor total para registros com `status` igual a 'ENTREGUE' E `valor_total` maior que 300.00.

In [40]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NUM_PEDIDO,\n    VALOR_TOTAL\nFROM PEDIDOS\nWHERE 1=1\nAND STATUS = \'ENTREGUE\'\nAND VALOR_TOTAL > 300',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   num_pedido  valor_total
0        5006        310.0

### Exercício 11 

**Contexto**

Para o fechamento mensal, a contabilidade precisa ignorar os pedidos que não geraram receita efetiva para a loja. O analista deve extrair todos os registros de pedidos do banco de dados, exceto aqueles que foram marcados com o status 'CANCELADO'. Além disso, para focar nas vendas que realmente impactam o faturamento, devem ser considerados apenas os pedidos com `valor_total` maior ou igual a 300,00. Esse filtro é essencial para que a projeção de faturamento não seja inflada por vendas não concretizadas ou de valor irrisório.

**Dados disponíveis**

Tabela: `pedidos`  
Colunas: `num_pedido`, `data_pedido`, `id_cliente`, `valor_total`, `status`

**Tarefa**

* Escreva uma query que retorne todas as colunas da tabela `pedidos` onde o `status` seja diferente de `'CANCELADO'` **e** o `valor_total` seja maior ou igual que 300,00 **ou** a data do pedido seja depois de `2024-02-01`

In [49]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NUM_PEDIDO,\n    DATA_PEDIDO,\n    ID_CLIENTE,\n    VALOR_TOTAL,\n    STATUS\nFROM PEDIDOS\nWHERE STATUS <> \'CANCELADO\'AND (VALOR_TOTAL >= 300 OR DATA_PEDIDO > \'2024-02-01\')',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   num_pedido data_pedido  id_cliente  valor_total       status
0        5002  2024-01-10         104       1200.0      ENVIADO
1        5004  2024-01-15         109       5500.0  PROCESSANDO
2        5006  2024-01-20         112        310.0     ENTREGUE
3        5007  2024-01-22         105        890.0      ENVIADO
4        5013  2024-02-05         110         85.0      ENVIADO

## A partir deste ponto, os exercícios podem ser feitos em grupo.

### Exercício 12 

**Contexto**
A equipe de controladoria está analisando pedidos realizados no início de 2024 para identificar tendências de compras de baixo valor que podem indicar erros de sistema. O analista precisa encontrar pedidos realizados a partir do dia '2024-01-20' cujo valor total seja inferior a 200, ou que ainda estejam processando para verificar erros. O impacto esperado é a correção de possíveis falhas na precificação de fretes.

**Dados disponíveis**
Tabela: `pedidos`
Colunas: `num_pedido`, `data_pedido`, `id_cliente`, `valor_total`, `status`

**Tarefa**
* Escreva uma query que retorne os pedidos com `data_pedido` maior ou igual a `2024-01-20` E `valor_total` menor que 200.00 ou o status como `PROCESSANDO`.

In [52]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NUM_PEDIDO,\n    DATA_PEDIDO,\n    ID_CLIENTE,\n    VALOR_TOTAL,\n    STATUS\nFROM PEDIDOS\nWHERE DATA_PEDIDO >= \'2024-01-20\' AND (VALOR_TOTAL < 200 OR STATUS = \'PROCESSANDO\')',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   num_pedido data_pedido  id_cliente  valor_total       status
0        5008  2024-01-25         108        130.0     ENTREGUE
1        5009  2024-01-26         111        290.0  PROCESSANDO
2        5010  2024-01-28         106        180.0     ENTREGUE
3        5013  2024-02-05         110         85.0      ENVIADO

### Exercício 13 

**Contexto**
O departamento de Recursos Humanos está atualizando o organograma da empresa para a reunião trimestral de resultados. Para facilitar a parabenização dos vendedores de bom desempenho foi solicitada uma lista simples contendo o nome do vendedor e região de atuação daqueles que bateram a meta. Por motivos de agendamento, os vendedores do `Sudeste`não puderam comparecer. O impacto esperado é uma comunicação interna mais eficiente entre as sedes regionais.

**Dados disponíveis**
Tabela: `vendedores`
Colunas: `id_vendedor`, `nome_vendedor`, `regiao`, `vendas_mes`, `meta_atingida`

**Tarefa**
* Escreva uma query que selecione as colunas `nome_vendedor` e `regiao` dos registros da tabela de vendedores que tenham atingido a meta e não sejam do `Sudeste`.

In [58]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NOME_VENDEDOR,\n    REGIAO\nFROM VENDEDORES\nWHERE META_ATINGIDA = \'SIM\' AND REGIAO <> \'Sudeste\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

  nome_vendedor    regiao
0         Aline  Nordeste
1        Carlos       Sul
2         Ivone  Nordeste

### Exercício 14 

**Contexto**

A gerência de vendas deseja premiar os funcionários que demonstraram excelência em uma das áreas mais competitivas da empresa. O objetivo é identificar os vendedores da região `'Sudeste'` que conseguiram atingir a meta estipulada no mês vigente **e** que superaram a marca de 40 vendas no mês. Esses dados servirão de base para o cálculo do bônus de performance que será pago na próxima folha.

**Dados disponíveis**

Tabela: `vendedores`  
Colunas: `id_vendedor`, `nome_vendedor`, `regiao`, `vendas_mes`, `meta_atingida`

**Tarefa**

* Escreva uma query que retorne o nome e a quantidade de vendas do mês (`vendas_mes`) dos vendedores que pertencem à `regiao` `'Sudeste'` **e** que tenham atingido a meta **e** possuam `vendas_mes` maior que 40.

In [61]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT \n    NOME_VENDEDOR,\n    VENDAS_MES\nFROM VENDEDORES\nWHERE 1=1\nAND REGIAO = \'Sudeste\'\nAND META_ATINGIDA = \'SIM\'\nAND VENDAS_MES > 40',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

  nome_vendedor  vendas_mes
0       Ricardo          45
1       Roberto          52
2       Beatriz          60

### Exercício 15 

**Contexto**
O analista de produtividade está classificando os vendedores em faixas de desempenho intermediário para oferecer treinamentos específicos. Ele precisa extrair a lista de colaboradores que realizaram mais de 20 vendas, mas que não ultrapassaram o limite de 40 vendas no mês. O impacto esperado é o desenvolvimento de um plano de carreira focado em aumentar a conversão.

**Dados disponíveis**
Tabela: `vendedores`
Colunas: `id_vendedor`, `nome_vendedor`, `regiao`, `vendas_mes`, `meta_atingida`

**Tarefa**
* Escreva uma query que retorne todos os dados dos vendedores que possuem `vendas_mes` maior que 20 E `vendas_mes` menor que 40.

In [73]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    ID_VENDEDOR,\n    NOME_VENDEDOR,\n    REGIAO,\n    VENDAS_MES,\n    META_ATINGIDA\nFROM VENDEDORES\nWHERE 1=1\nAND VENDAS_MES > 20\nAND VENDAS_MES < 40',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

   id_vendedor nome_vendedor    regiao  vendas_mes meta_atingida
0            2        Marcia       Sul          28           NAO
1            4         Aline  Nordeste          33           SIM
2            8       Daniela  Nordeste          25           NAO
3           10        Gisele   Sudeste          38           SIM
4           11          Hugo       Sul          22           NAO

### Exercício 16 

**Contexto**

O diretor comercial está organizando uma conferência regional e precisa convocar todos os vendedores que atuam nas extremidades do país para um alinhamento estratégico. Para simplificar a query, o analista deve buscar vendedores que estejam alocados nas regiões `'Sul'` ou `'Norte'`. Além disso, para reforçar a cultura de alta performance, devem ser incluídos somente aqueles que atingiram a meta do mês (`'meta_atingida'` = `'SIM'`). Essa segmentação facilitará a logística de passagens e hospedagens para o evento.

**Dados disponíveis**

Tabela: `vendedores`  
Colunas: `id_vendedor`, `nome_vendedor`, `regiao`, `vendas_mes`, `meta_atingida`

**Tarefa**

* Escreva uma query que retorne o `nome_vendedor` e a `regiao` dos vendedores cuja `regiao` esteja entre as opções `'Sul'` ou `'Norte'` **e** que tenham `meta_atingida` igual a `'SIM'`.

In [76]:
if '_dntk' in globals():
  _dntk.dataframe_utils.configure_dataframe_formatter('{}')
else:
  _deepnote_current_table_attrs = '{}'

_dntk.execute_sql(
  'SELECT\n    NOME_VENDEDOR,\n    REGIAO\nFROM VENDEDORES\nWHERE REGIAO IN (\'Sul\', \'Norte\') AND META_ATINGIDA = \'SIM\'',
  'SQL_DEEPNOTE_DATAFRAME_SQL',
  audit_sql_comment='',
  sql_cache_mode='cache_disabled',
  return_variable_type='dataframe'
)

  nome_vendedor regiao
0        Carlos    Sul

# Instruções para Entrega

## Permissão Pública e Desligando assistente de IA

Primeiro é necessário ligar a permissão de compartilhamento com link e desligar o assistente de IA. Siga o procedimento:
1. Clique na foto do seu usuário no canto superior direito e depois selecione 'Account Settings'

<img src="image-20250206-210028.png" width="" align="" />

2. Do lado esquerdo, selecione o seu workspace onde seu TP será colocado (no caso o workspace Meus Trabalhos foi selecionado)
3. Depois seleciona e opção 'Settings & members'

<img src="image-20250206-210139.png" width="" align="" />

4. Clique em 'Project Settings'
5. Desmarque todas as opções relacionadas a IA
6. Ligue a opção 'Allow projects to be shared publicity'

<img src="image-20250206-210654.png" width="" align="" />

## Criando Link para entregar

Assim que terminar, siga o procedimento:

1) Primeiro clique em Duplicate para copiar o projeto
2) Clique em **Share** no canto superior direito.
2) Ao lado de "Anyone with a link to this project" clique e selecione a opção **"Edit"**.
3) Clique em "Copy Link" e guarde o link do seu projeto.
4) Crie um PDF com nome **nome_sobrenome_DR2_TP1.pdf** com o link do projeto e coloque faça o _upload_ no Moodle.

<img src="image-20250205-220400.png" width="" align="" />

<img src="image-20250205-220422.png" width="" align="" />

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=6b7f6232-6106-4f77-a13f-c308d41ef5f9' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>